[project]
name = "juicenet-cli"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "annotated-types==0.7.0 ; python_full_version >= '3.9' and python_full_version < '4.0'",
    "attrs==23.2.0 ; python_full_version >= '3.9' and python_full_version < '4.0'",
    "colorama==0.4.6 ; python_full_version >= '3.9' and python_full_version < '4.0'",
    "cyclopts==2.9.3 ; python_full_version >= '3.9' and python_full_version < '4.0'",
    "docstring-parser==0.16 ; python_full_version >= '3.9' and python_full_version < '4.0'",
    "docutils==0.21.2 ; python_full_version >= '3.9' and python_full_version < '4.0'",
    "importlib-metadata==8.0.0 ; python_full_version == '3.9.*'",
    "loguru==0.7.2 ; python_full_version >= '3.9' and python_full_version < '4.0'",
    "markdown-it-py==3.0.0 ; python_full_version >= '3.9' and python_full_version < '4.0'",
    "mdurl==0.1.2 ; python_full_version >= '3.9' and python_full_version < '4.0'",
    "natsort==8.4.0 ; python_full_version >= '3.9' and python_full_version < '4.0'",
    "pydantic-core==2.20.1 ; python_full_version >= '3.9' and python_full_version < '4.0'",
    "pydantic==2.8.2 ; python_full_version >= '3.9' and python_full_version < '4.0'",
    "pygments==2.18.0 ; python_full_version >= '3.9' and python_full_version < '4.0'",
    "pyyaml==6.0.1 ; python_full_version >= '3.9' and python_full_version < '4.0'",
    "rich-rst==1.3.1 ; python_full_version >= '3.9' and python_full_version < '4.0'",
    "rich==13.7.1 ; python_full_version >= '3.9' and python_full_version < '4.0'",
    "strenum==0.4.15 ; python_full_version >= '3.9' and python_full_version < '3.11'",
    "typing-extensions==4.12.2 ; python_full_version >= '3.9' and python_full_version < '4.0'",
    "win32-setctime==1.1.0 ; python_full_version >= '3.9' and python_full_version < '4.0' and sys_platform == 'win32'",
    "zipp==3.19.2 ; python_full_version == '3.9.*'",
    "babel==2.15.0 ; python_full_version >= '3.9' and python_full_version < '4.0'",
    "certifi==2024.7.4 ; python_full_version >= '3.9' and python_full_version < '4.0'",
    "cfgv==3.4.0 ; python_full_version >= '3.9' and python_full_version < '4.0'",
    "charset-normalizer==3.3.2 ; python_full_version >= '3.9' and python_full_version < '4.0'",
    "click==8.1.7 ; python_full_version >= '3.9' and python_full_version < '4.0'",
    "distlib==0.3.8 ; python_full_version >= '3.9' and python_full_version < '4.0'",
    "filelock==3.15.4 ; python_full_version >= '3.9' and python_full_version < '4.0'",
    "ghp-import==2.1.0 ; python_full_version >= '3.9' and python_full_version < '4.0'",
    "griffe==0.47.0 ; python_full_version >= '3.9' and python_full_version < '4.0'",
    "identify==2.5.36 ; python_full_version >= '3.9' and python_full_version < '4.0'",
    "idna==3.7 ; python_full_version >= '3.9' and python_full_version < '4.0'",
    "jinja2==3.1.4 ; python_full_version >= '3.9' and python_full_version < '4.0'",
    "loguru-mypy==0.0.4 ; python_full_version >= '3.9' and python_full_version < '4.0'",
    "markdown==3.6 ; python_full_version >= '3.9' and python_full_version < '4.0'",
    "markupsafe==2.1.5 ; python_full_version >= '3.9' and python_full_version < '4.0'",
    "mergedeep==1.3.4 ; python_full_version >= '3.9' and python_full_version < '4.0'",
    "mkdocs-autorefs==1.0.1 ; python_full_version >= '3.9' and python_full_version < '4.0'",
    "mkdocs-get-deps==0.2.0 ; python_full_version >= '3.9' and python_full_version < '4.0'",
    "mkdocs-material-extensions==1.3.1 ; python_full_version >= '3.9' and python_full_version < '4.0'",
    "mkdocs-material==9.5.28 ; python_full_version >= '3.9' and python_full_version < '4.0'",
    "mkdocs==1.6.0 ; python_full_version >= '3.9' and python_full_version < '4.0'",
    "mkdocstrings-python==1.10.5 ; python_full_version >= '3.9' and python_full_version < '4.0'",
    "mkdocstrings[python]==0.25.1 ; python_full_version >= '3.9' and python_full_version < '4.0'",
    "mypy-extensions==1.0.0 ; python_full_version >= '3.9' and python_full_version < '4.0'",
    "mypy==1.10.1 ; python_full_version >= '3.9' and python_full_version < '4.0'",
    "nodeenv==1.9.1 ; python_full_version >= '3.9' and python_full_version < '4.0'",
    "packaging==24.1 ; python_full_version >= '3.9' and python_full_version < '4.0'",
    "paginate==0.5.6 ; python_full_version >= '3.9' and python_full_version < '4.0'",
    "pathspec==0.12.1 ; python_full_version >= '3.9' and python_full_version < '4.0'",
    "platformdirs==4.2.2 ; python_full_version >= '3.9' and python_full_version < '4.0'",
    "pre-commit==3.7.1 ; python_full_version >= '3.9' and python_full_version < '4.0'",
    "pymdown-extensions==10.8.1 ; python_full_version >= '3.9' and python_full_version < '4.0'",
    "python-dateutil==2.9.0.post0 ; python_full_version >= '3.9' and python_full_version < '4.0'",
    "pyyaml-env-tag==0.1 ; python_full_version >= '3.9' and python_full_version < '4.0'",
    "regex==2024.5.15 ; python_full_version >= '3.9' and python_full_version < '4.0'",
    "requests==2.32.3 ; python_full_version >= '3.9' and python_full_version < '4.0'",
    "ruff==0.5.1 ; python_full_version >= '3.9' and python_full_version < '4.0'",
    "six==1.16.0 ; python_full_version >= '3.9' and python_full_version < '4.0'",
    "tomli==2.0.1 ; python_full_version >= '3.9' and python_full_version < '3.11'",
    "urllib3==2.2.2 ; python_full_version >= '3.9' and python_full_version < '4.0'",
    "virtualenv==20.26.3 ; python_full_version >= '3.9' and python_full_version < '4.0'",
    "watchdog==4.0.1 ; python_full_version >= '3.9' and python_full_version < '4.0'",
    "loguru>=0.7.2",
]
